# Generated by Django 2.1 on 2018-08-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='entry_type',
            field=models.CharField(choices=[('connection', 'connection'), ('location', 'location')], max_length=20),
        ),
    ]
